version: '3'

services:
  awlc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: awlc
    ports:
      - "1880:1880"  # Node-RED web interface
      - "1883:1883"  # MQTT broker
      - "9001:9001"  # MQTT websockets (if needed)
    volumes:
      - ../node-red/flows:/app/node-red/flows
      - node_red_data:/data
    restart: unless-stopped

volumes:
  node_red_data:
